version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: test_postgres_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user" ]
      interval: 10s
      timeout: 5s
      retries: 5