version: "3.9"
services:
  postgres:
    image: postgres:16
    env_file: [ .env ]
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports: [ "5432:5432" ]

  api:
    build: .
    env_file: [ .env ]
    command: >
      bash -lc "
      ./scripts/wait-for-db.sh &&
      pipenv run alembic upgrade head &&
      pipenv run uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-8000} --reload
      "
    volumes: 
      - ".:/code"
      - "/code/.venv"
    depends_on:
      postgres:
        condition: service_healthy
    ports: [ "${APP_PORT:-8000}:8000" ]

volumes:
  pgdata: