"""Initiazlie migration

Revision ID: 221c5c782e14
Revises: 
Create Date: 2025-01-16 01:08:11.749607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221c5c782e14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apos_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_centers_apos_id'), 'test_centers', ['apos_id'], unique=False)
    op.create_index(op.f('ix_test_centers_city'), 'test_centers', ['city'], unique=False)
    op.create_index(op.f('ix_test_centers_id'), 'test_centers', ['id'], unique=False)
    op.create_index(op.f('ix_test_centers_name'), 'test_centers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_centers_name'), table_name='test_centers')
    op.drop_index(op.f('ix_test_centers_id'), table_name='test_centers')
    op.drop_index(op.f('ix_test_centers_city'), table_name='test_centers')
    op.drop_index(op.f('ix_test_centers_apos_id'), table_name='test_centers')
    op.drop_table('test_centers')
    # ### end Alembic commands ###
