"""test centers updated

Revision ID: 36195a9a0d1d
Revises: 5cea43e0e2a4
Create Date: 2025-02-03 21:21:59.057074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36195a9a0d1d'
down_revision: Union[str, None] = '5cea43e0e2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_centers', sa.Column('pos_id', sa.Integer(), nullable=False))
    op.add_column('test_centers', sa.Column('url', sa.String(), nullable=False))
    op.add_column('test_centers', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('test_centers', sa.Column('lat', sa.Integer(), nullable=False))
    op.add_column('test_centers', sa.Column('lng', sa.Integer(), nullable=False))
    op.alter_column('test_centers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('test_centers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('test_centers', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'test_centers', ['postal_code'])
    op.create_unique_constraint(None, 'test_centers', ['url'])
    op.create_unique_constraint(None, 'test_centers', ['pos_id'])
    op.create_unique_constraint(None, 'test_centers', ['address'])
    op.create_unique_constraint(None, 'test_centers', ['name'])
    op.drop_column('test_centers', 'apos_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_centers', sa.Column('apos_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_centers', type_='unique')
    op.drop_constraint(None, 'test_centers', type_='unique')
    op.drop_constraint(None, 'test_centers', type_='unique')
    op.drop_constraint(None, 'test_centers', type_='unique')
    op.drop_constraint(None, 'test_centers', type_='unique')
    op.alter_column('test_centers', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('test_centers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('test_centers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('test_centers', 'lng')
    op.drop_column('test_centers', 'lat')
    op.drop_column('test_centers', 'postal_code')
    op.drop_column('test_centers', 'url')
    op.drop_column('test_centers', 'pos_id')
    # ### end Alembic commands ###
