"""user_prefrences_and_lead_added

Revision ID: 376480152abe
Revises: 221c5c782e14
Create Date: 2025-01-24 16:24:07.776963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376480152abe'
down_revision: Union[str, None] = '221c5c782e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('user_preferences_centers',
    sa.Column('user_preference_id', sa.String(), nullable=True),
    sa.Column('test_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_center_id'], ['test_centers.id'], ),
    sa.ForeignKeyConstraint(['user_preference_id'], ['user_preferences.id'], )
    )
    op.drop_index('ix_test_centers_apos_id', table_name='test_centers')
    op.drop_index('ix_test_centers_city', table_name='test_centers')
    op.drop_index('ix_test_centers_name', table_name='test_centers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_test_centers_name', 'test_centers', ['name'], unique=False)
    op.create_index('ix_test_centers_city', 'test_centers', ['city'], unique=False)
    op.create_index('ix_test_centers_apos_id', 'test_centers', ['apos_id'], unique=False)
    op.drop_table('user_preferences_centers')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
